name: Build

on:
  push:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Install nbgv
      run: dotnet tool install nbgv --tool-path ./tools --version 3.3.37
    - name: Run nbgv
      run: echo "NUGET_PACKAGE_VERSION=$(./tools/nbgv get-version -v NuGetPackageVersion)" >> $GITHUB_ENV
      
    - name: Pack 
      run: dotnet pack --output ./out --configuration Release --verbosity normal

    - name: Run nbgv
      env:
        FILE_NAME: "test-actions.$NUGET_PACKAGE_VERSION-beta"
      run: echo "FileName $FILE_NAME"

    # - name: Upload nupkg Release Asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     FILE_NAME: "DevHawk.Buffers.$NUGET_PACKAGE_VERSION.nupkg"
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: "./out/$FILE_NAME"
    #     asset_name: "$FILE_NAME"
    #     asset_content_type: application/zip

    # - name: Upload snupkg Release Asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     FILE_NAME: "DevHawk.Buffers.$NUGET_PACKAGE_VERSION.snupkg"
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: "./out/$FILE_NAME"
    #     asset_name: "$FILE_NAME"
    #     asset_content_type: application/zip
